// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: stakeholders/stakeholders.proto

package stakeholders

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserRole int32

const (
	UserRole_Administrator UserRole = 0
	UserRole_Tourist       UserRole = 1
	UserRole_Author        UserRole = 2
)

// Enum value maps for UserRole.
var (
	UserRole_name = map[int32]string{
		0: "Administrator",
		1: "Tourist",
		2: "Author",
	}
	UserRole_value = map[string]int32{
		"Administrator": 0,
		"Tourist":       1,
		"Author":        2,
	}
)

func (x UserRole) Enum() *UserRole {
	p := new(UserRole)
	*p = x
	return p
}

func (x UserRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserRole) Descriptor() protoreflect.EnumDescriptor {
	return file_stakeholders_stakeholders_proto_enumTypes[0].Descriptor()
}

func (UserRole) Type() protoreflect.EnumType {
	return &file_stakeholders_stakeholders_proto_enumTypes[0]
}

func (x UserRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserRole.Descriptor instead.
func (UserRole) EnumDescriptor() ([]byte, []int) {
	return file_stakeholders_stakeholders_proto_rawDescGZIP(), []int{0}
}

type UsersPagedResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Results        []*UserResponse        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	TotalCount     int32                  `protobuf:"varint,2,opt,name=totalCount,proto3" json:"totalCount,omitempty"`
	RemainingCount int32                  `protobuf:"varint,3,opt,name=remainingCount,proto3" json:"remainingCount,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UsersPagedResponse) Reset() {
	*x = UsersPagedResponse{}
	mi := &file_stakeholders_stakeholders_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsersPagedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsersPagedResponse) ProtoMessage() {}

func (x *UsersPagedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stakeholders_stakeholders_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsersPagedResponse.ProtoReflect.Descriptor instead.
func (*UsersPagedResponse) Descriptor() ([]byte, []int) {
	return file_stakeholders_stakeholders_proto_rawDescGZIP(), []int{0}
}

func (x *UsersPagedResponse) GetResults() []*UserResponse {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *UsersPagedResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *UsersPagedResponse) GetRemainingCount() int32 {
	if x != nil {
		return x.RemainingCount
	}
	return 0
}

type EmptyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyRequest) Reset() {
	*x = EmptyRequest{}
	mi := &file_stakeholders_stakeholders_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyRequest) ProtoMessage() {}

func (x *EmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stakeholders_stakeholders_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyRequest.ProtoReflect.Descriptor instead.
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return file_stakeholders_stakeholders_proto_rawDescGZIP(), []int{1}
}

type ToggleBlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleBlockRequest) Reset() {
	*x = ToggleBlockRequest{}
	mi := &file_stakeholders_stakeholders_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleBlockRequest) ProtoMessage() {}

func (x *ToggleBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stakeholders_stakeholders_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleBlockRequest.ProtoReflect.Descriptor instead.
func (*ToggleBlockRequest) Descriptor() ([]byte, []int) {
	return file_stakeholders_stakeholders_proto_rawDescGZIP(), []int{2}
}

func (x *ToggleBlockRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ToggleBlockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleBlockResponse) Reset() {
	*x = ToggleBlockResponse{}
	mi := &file_stakeholders_stakeholders_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleBlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleBlockResponse) ProtoMessage() {}

func (x *ToggleBlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stakeholders_stakeholders_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleBlockResponse.ProtoReflect.Descriptor instead.
func (*ToggleBlockResponse) Descriptor() ([]byte, []int) {
	return file_stakeholders_stakeholders_proto_rawDescGZIP(), []int{3}
}

func (x *ToggleBlockResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type PersonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Surname       string                 `protobuf:"bytes,3,opt,name=surname,proto3" json:"surname,omitempty"`
	Bio           string                 `protobuf:"bytes,4,opt,name=bio,proto3" json:"bio,omitempty"`
	Moto          string                 `protobuf:"bytes,5,opt,name=moto,proto3" json:"moto,omitempty"`
	PictureBase64 string                 `protobuf:"bytes,6,opt,name=pictureBase64,proto3" json:"pictureBase64,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PersonResponse) Reset() {
	*x = PersonResponse{}
	mi := &file_stakeholders_stakeholders_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonResponse) ProtoMessage() {}

func (x *PersonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stakeholders_stakeholders_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonResponse.ProtoReflect.Descriptor instead.
func (*PersonResponse) Descriptor() ([]byte, []int) {
	return file_stakeholders_stakeholders_proto_rawDescGZIP(), []int{4}
}

func (x *PersonResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PersonResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PersonResponse) GetSurname() string {
	if x != nil {
		return x.Surname
	}
	return ""
}

func (x *PersonResponse) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *PersonResponse) GetMoto() string {
	if x != nil {
		return x.Moto
	}
	return ""
}

func (x *PersonResponse) GetPictureBase64() string {
	if x != nil {
		return x.PictureBase64
	}
	return ""
}

type PagedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PagedRequest) Reset() {
	*x = PagedRequest{}
	mi := &file_stakeholders_stakeholders_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PagedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PagedRequest) ProtoMessage() {}

func (x *PagedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stakeholders_stakeholders_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PagedRequest.ProtoReflect.Descriptor instead.
func (*PagedRequest) Descriptor() ([]byte, []int) {
	return file_stakeholders_stakeholders_proto_rawDescGZIP(), []int{5}
}

func (x *PagedRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PagedRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type UserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Role          UserRole               `protobuf:"varint,4,opt,name=role,proto3,enum=stakeholders.UserRole" json:"role,omitempty"`
	IsBlocked     bool                   `protobuf:"varint,5,opt,name=isBlocked,proto3" json:"isBlocked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResponse) Reset() {
	*x = UserResponse{}
	mi := &file_stakeholders_stakeholders_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse) ProtoMessage() {}

func (x *UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stakeholders_stakeholders_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse.ProtoReflect.Descriptor instead.
func (*UserResponse) Descriptor() ([]byte, []int) {
	return file_stakeholders_stakeholders_proto_rawDescGZIP(), []int{6}
}

func (x *UserResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserResponse) GetRole() UserRole {
	if x != nil {
		return x.Role
	}
	return UserRole_Administrator
}

func (x *UserResponse) GetIsBlocked() bool {
	if x != nil {
		return x.IsBlocked
	}
	return false
}

var File_stakeholders_stakeholders_proto protoreflect.FileDescriptor

const file_stakeholders_stakeholders_proto_rawDesc = "" +
	"\n" +
	"\x1fstakeholders/stakeholders.proto\x12\fstakeholders\"\x92\x01\n" +
	"\x12UsersPagedResponse\x124\n" +
	"\aresults\x18\x01 \x03(\v2\x1a.stakeholders.UserResponseR\aresults\x12\x1e\n" +
	"\n" +
	"totalCount\x18\x02 \x01(\x05R\n" +
	"totalCount\x12&\n" +
	"\x0eremainingCount\x18\x03 \x01(\x05R\x0eremainingCount\"\x0e\n" +
	"\fEmptyRequest\"$\n" +
	"\x12ToggleBlockRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"/\n" +
	"\x13ToggleBlockResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x9a\x01\n" +
	"\x0ePersonResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\asurname\x18\x03 \x01(\tR\asurname\x12\x10\n" +
	"\x03bio\x18\x04 \x01(\tR\x03bio\x12\x12\n" +
	"\x04moto\x18\x05 \x01(\tR\x04moto\x12$\n" +
	"\rpictureBase64\x18\x06 \x01(\tR\rpictureBase64\">\n" +
	"\fPagedRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x05R\bpageSize\"\x9a\x01\n" +
	"\fUserResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12*\n" +
	"\x04role\x18\x04 \x01(\x0e2\x16.stakeholders.UserRoleR\x04role\x12\x1c\n" +
	"\tisBlocked\x18\x05 \x01(\bR\tisBlocked*6\n" +
	"\bUserRole\x12\x11\n" +
	"\rAdministrator\x10\x00\x12\v\n" +
	"\aTourist\x10\x01\x12\n" +
	"\n" +
	"\x06Author\x10\x022W\n" +
	"\rPersonService\x12F\n" +
	"\n" +
	"GetProfile\x12\x1a.stakeholders.EmptyRequest\x1a\x1c.stakeholders.PersonResponse2\xab\x01\n" +
	"\vUserService\x12H\n" +
	"\bGetPaged\x12\x1a.stakeholders.PagedRequest\x1a .stakeholders.UsersPagedResponse\x12R\n" +
	"\vToggleBlock\x12 .stakeholders.ToggleBlockRequest\x1a!.stakeholders.ToggleBlockResponseB\x15Z\x13Protos/stakeholdersb\x06proto3"

var (
	file_stakeholders_stakeholders_proto_rawDescOnce sync.Once
	file_stakeholders_stakeholders_proto_rawDescData []byte
)

func file_stakeholders_stakeholders_proto_rawDescGZIP() []byte {
	file_stakeholders_stakeholders_proto_rawDescOnce.Do(func() {
		file_stakeholders_stakeholders_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stakeholders_stakeholders_proto_rawDesc), len(file_stakeholders_stakeholders_proto_rawDesc)))
	})
	return file_stakeholders_stakeholders_proto_rawDescData
}

var file_stakeholders_stakeholders_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_stakeholders_stakeholders_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_stakeholders_stakeholders_proto_goTypes = []any{
	(UserRole)(0),               // 0: stakeholders.UserRole
	(*UsersPagedResponse)(nil),  // 1: stakeholders.UsersPagedResponse
	(*EmptyRequest)(nil),        // 2: stakeholders.EmptyRequest
	(*ToggleBlockRequest)(nil),  // 3: stakeholders.ToggleBlockRequest
	(*ToggleBlockResponse)(nil), // 4: stakeholders.ToggleBlockResponse
	(*PersonResponse)(nil),      // 5: stakeholders.PersonResponse
	(*PagedRequest)(nil),        // 6: stakeholders.PagedRequest
	(*UserResponse)(nil),        // 7: stakeholders.UserResponse
}
var file_stakeholders_stakeholders_proto_depIdxs = []int32{
	7, // 0: stakeholders.UsersPagedResponse.results:type_name -> stakeholders.UserResponse
	0, // 1: stakeholders.UserResponse.role:type_name -> stakeholders.UserRole
	2, // 2: stakeholders.PersonService.GetProfile:input_type -> stakeholders.EmptyRequest
	6, // 3: stakeholders.UserService.GetPaged:input_type -> stakeholders.PagedRequest
	3, // 4: stakeholders.UserService.ToggleBlock:input_type -> stakeholders.ToggleBlockRequest
	5, // 5: stakeholders.PersonService.GetProfile:output_type -> stakeholders.PersonResponse
	1, // 6: stakeholders.UserService.GetPaged:output_type -> stakeholders.UsersPagedResponse
	4, // 7: stakeholders.UserService.ToggleBlock:output_type -> stakeholders.ToggleBlockResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_stakeholders_stakeholders_proto_init() }
func file_stakeholders_stakeholders_proto_init() {
	if File_stakeholders_stakeholders_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stakeholders_stakeholders_proto_rawDesc), len(file_stakeholders_stakeholders_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_stakeholders_stakeholders_proto_goTypes,
		DependencyIndexes: file_stakeholders_stakeholders_proto_depIdxs,
		EnumInfos:         file_stakeholders_stakeholders_proto_enumTypes,
		MessageInfos:      file_stakeholders_stakeholders_proto_msgTypes,
	}.Build()
	File_stakeholders_stakeholders_proto = out.File
	file_stakeholders_stakeholders_proto_goTypes = nil
	file_stakeholders_stakeholders_proto_depIdxs = nil
}
