// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: authentication.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CredentialsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredentialsRequest) Reset() {
	*x = CredentialsRequest{}
	mi := &file_authentication_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialsRequest) ProtoMessage() {}

func (x *CredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authentication_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialsRequest.ProtoReflect.Descriptor instead.
func (*CredentialsRequest) Descriptor() ([]byte, []int) {
	return file_authentication_proto_rawDescGZIP(), []int{0}
}

func (x *CredentialsRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CredentialsRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AccountRegistrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Surname       string                 `protobuf:"bytes,4,opt,name=surname,proto3" json:"surname,omitempty"`
	Bio           string                 `protobuf:"bytes,5,opt,name=bio,proto3" json:"bio,omitempty"`
	PictureBase64 string                 `protobuf:"bytes,6,opt,name=pictureBase64,proto3" json:"pictureBase64,omitempty"`
	Moto          string                 `protobuf:"bytes,7,opt,name=moto,proto3" json:"moto,omitempty"`
	Email         string                 `protobuf:"bytes,8,opt,name=email,proto3" json:"email,omitempty"`
	Role          string                 `protobuf:"bytes,9,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountRegistrationRequest) Reset() {
	*x = AccountRegistrationRequest{}
	mi := &file_authentication_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountRegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountRegistrationRequest) ProtoMessage() {}

func (x *AccountRegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authentication_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountRegistrationRequest.ProtoReflect.Descriptor instead.
func (*AccountRegistrationRequest) Descriptor() ([]byte, []int) {
	return file_authentication_proto_rawDescGZIP(), []int{1}
}

func (x *AccountRegistrationRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AccountRegistrationRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *AccountRegistrationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AccountRegistrationRequest) GetSurname() string {
	if x != nil {
		return x.Surname
	}
	return ""
}

func (x *AccountRegistrationRequest) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *AccountRegistrationRequest) GetPictureBase64() string {
	if x != nil {
		return x.PictureBase64
	}
	return ""
}

func (x *AccountRegistrationRequest) GetMoto() string {
	if x != nil {
		return x.Moto
	}
	return ""
}

func (x *AccountRegistrationRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AccountRegistrationRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type AuthenticationTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	Id            int64                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticationTokenResponse) Reset() {
	*x = AuthenticationTokenResponse{}
	mi := &file_authentication_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticationTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticationTokenResponse) ProtoMessage() {}

func (x *AuthenticationTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authentication_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticationTokenResponse.ProtoReflect.Descriptor instead.
func (*AuthenticationTokenResponse) Descriptor() ([]byte, []int) {
	return file_authentication_proto_rawDescGZIP(), []int{2}
}

func (x *AuthenticationTokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *AuthenticationTokenResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ValidateTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsValid       bool                   `protobuf:"varint,2,opt,name=isValid,proto3" json:"isValid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenResponse) Reset() {
	*x = ValidateTokenResponse{}
	mi := &file_authentication_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenResponse) ProtoMessage() {}

func (x *ValidateTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authentication_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenResponse.ProtoReflect.Descriptor instead.
func (*ValidateTokenResponse) Descriptor() ([]byte, []int) {
	return file_authentication_proto_rawDescGZIP(), []int{3}
}

func (x *ValidateTokenResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

type EmptyMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyMessage) Reset() {
	*x = EmptyMessage{}
	mi := &file_authentication_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyMessage) ProtoMessage() {}

func (x *EmptyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_authentication_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyMessage.ProtoReflect.Descriptor instead.
func (*EmptyMessage) Descriptor() ([]byte, []int) {
	return file_authentication_proto_rawDescGZIP(), []int{4}
}

var File_authentication_proto protoreflect.FileDescriptor

const file_authentication_proto_rawDesc = "" +
	"\n" +
	"\x14authentication.proto\x12\x04auth\"F\n" +
	"\x12CredentialsRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\xf8\x01\n" +
	"\x1aAccountRegistrationRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\asurname\x18\x04 \x01(\tR\asurname\x12\x10\n" +
	"\x03bio\x18\x05 \x01(\tR\x03bio\x12$\n" +
	"\rpictureBase64\x18\x06 \x01(\tR\rpictureBase64\x12\x12\n" +
	"\x04moto\x18\a \x01(\tR\x04moto\x12\x14\n" +
	"\x05email\x18\b \x01(\tR\x05email\x12\x12\n" +
	"\x04role\x18\t \x01(\tR\x04role\"O\n" +
	"\x1bAuthenticationTokenResponse\x12 \n" +
	"\vaccessToken\x18\x01 \x01(\tR\vaccessToken\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x03R\x02id\"1\n" +
	"\x15ValidateTokenResponse\x12\x18\n" +
	"\aisValid\x18\x02 \x01(\bR\aisValid\"\x0e\n" +
	"\fEmptyMessage2\xe6\x01\n" +
	"\vAuthService\x12@\n" +
	"\rValidateToken\x12\x12.auth.EmptyMessage\x1a\x1b.auth.ValidateTokenResponse\x12D\n" +
	"\x05Login\x12\x18.auth.CredentialsRequest\x1a!.auth.AuthenticationTokenResponse\x12O\n" +
	"\bRegister\x12 .auth.AccountRegistrationRequest\x1a!.auth.AuthenticationTokenResponseB\fZ\n" +
	"proto/authb\x06proto3"

var (
	file_authentication_proto_rawDescOnce sync.Once
	file_authentication_proto_rawDescData []byte
)

func file_authentication_proto_rawDescGZIP() []byte {
	file_authentication_proto_rawDescOnce.Do(func() {
		file_authentication_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_authentication_proto_rawDesc), len(file_authentication_proto_rawDesc)))
	})
	return file_authentication_proto_rawDescData
}

var file_authentication_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_authentication_proto_goTypes = []any{
	(*CredentialsRequest)(nil),          // 0: auth.CredentialsRequest
	(*AccountRegistrationRequest)(nil),  // 1: auth.AccountRegistrationRequest
	(*AuthenticationTokenResponse)(nil), // 2: auth.AuthenticationTokenResponse
	(*ValidateTokenResponse)(nil),       // 3: auth.ValidateTokenResponse
	(*EmptyMessage)(nil),                // 4: auth.EmptyMessage
}
var file_authentication_proto_depIdxs = []int32{
	4, // 0: auth.AuthService.ValidateToken:input_type -> auth.EmptyMessage
	0, // 1: auth.AuthService.Login:input_type -> auth.CredentialsRequest
	1, // 2: auth.AuthService.Register:input_type -> auth.AccountRegistrationRequest
	3, // 3: auth.AuthService.ValidateToken:output_type -> auth.ValidateTokenResponse
	2, // 4: auth.AuthService.Login:output_type -> auth.AuthenticationTokenResponse
	2, // 5: auth.AuthService.Register:output_type -> auth.AuthenticationTokenResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_authentication_proto_init() }
func file_authentication_proto_init() {
	if File_authentication_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_authentication_proto_rawDesc), len(file_authentication_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_authentication_proto_goTypes,
		DependencyIndexes: file_authentication_proto_depIdxs,
		MessageInfos:      file_authentication_proto_msgTypes,
	}.Build()
	File_authentication_proto = out.File
	file_authentication_proto_goTypes = nil
	file_authentication_proto_depIdxs = nil
}
